version: "3.9"

services:
  mp3quran:
    container_name: mp3quran
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker-compose/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker-compose/mp3quran.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - npm

  php:
    image: asarach/php8.2:1
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    command: sh -c "php-fpm"
    # run : " composer install"


  #MySQL Service
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mp3quran
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-compose/mysql.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mp3quran.sql:/tmp/database/mp3quran.sql
    # run: mysql -u root mp3quran < /tmp/database/mp3quran.sql -p

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8081:80


  npm:
    image: node:14
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    working_dir: /var/www/html
    command: sh -c "tail -f /dev/null"
    # run : " npm install"


#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local