<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Msurguy\\Honeypot\\' => array($vendorDir . '/msurguy/honeypot/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Mcamara\\LaravelLocalization' => array($vendorDir . '/mcamara/laravel-localization/src'),
    'Heroicpixels\\Filterable\\' => array($vendorDir . '/heroicpixels/filterable/src'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'Bhutanio\\BEncode' => array($vendorDir . '/bhutanio/laravel-bencode/src'),
);
